### ISSUE TITLE
Finalize list of resource types for Hyrax

### ISSUE THREAD

**Issue by vantuyls** [osulp/sa-content#1]
Need to examine the current lists of resource types in DSpace and Sufia to ensure that we have captured necessary resource types for the Sufia instance.

**Comment by vantuyls** [comment]
https://docs.google.com/spreadsheets/d/1x_P7WszhOoIKs-vfGrP5j9ichlWrJaa82ZnrHM8Z8no/edit#gid=0

**Comment by vantuyls** [comment]
Proposed final list is here: https://docs.google.com/spreadsheets/d/1x_P7WszhOoIKs-vfGrP5j9ichlWrJaa82ZnrHM8Z8no/edit#gid=311701783

Look at the **Proposed Final List** tab

**Comment by zhang4952** [comment]
I will close this ticket as the mapping has been reflected in the migration code.
