### ISSUE TITLE
ETD Work Type Needs All Predicates

### ISSUE THREAD

**Issue by vantuyls** [osulp/sa-content#10]

**Comment by zhang4952** [comment]
Check the updated version of Hyrax Work Type, the Generic and ETD types are in good shape now. The fields in dark orange should require we mint some local URIs as predicate. I think we should be take a balance on how many DSpace fields should be crosswalked to Hyrax as many of them are rarely used at all. I create this spreadsheet to demonstrate my point: https://docs.google.com/spreadsheets/d/1wI9VXerv4ju5E4df6CdzwXZ0JqhUH_rl2XrySIV8gOE/edit?usp=sharing

**Comment by vantuyls** [comment]
im all for trying to strike a balance with that list of DSpace fields in your spreadsheet. I think it is somewhat clear (?) that elements with 1 or 4 instances may not be worth bending over backwards to find predicates for and migrate "properly" but where do we draw the line? 

dc.format.extent seems to be a break point at 221 items. Thoughts?

**Comment by vantuyls** [comment]
Also, dcterms.isReferncedBy is obviously a problem given that the element itself has a spelling error in the name. does dcterms.isReferencedBy (no spelling error) exist elsewhere in DSpace that these 4 instances could be merged with the correctly spelled element?

**Comment by wickr** [comment]
Rarely used doesn't mean they're useless though. And I think we're finding predicates for most/all of these. Even the ones with small counts are mostly Dublin Core. Is PeerReviewNotes the only outstanding one right now? I'm not sure what's even in that field, I think that's more important than how many times it appears.

If bibtex.address is street address, there's ways to do that. Oregon Digital uses the field from MADS.

Identifier.govdoc I don't see one for right away, but likely exists or would probably be worth creating. I know there aren't many, but I don't believe it's worth losing information about identifiers.

**Comment by zhang4952** [comment]
Each ETD property has a predicate now, check the Hydra Work Type in Google drive: https://docs.google.com/spreadsheets/d/1IwifC3NBIHqBhNBZxQNlqYr6u-xBHYFs-025xNYaMik/edit#gid=1295494001
