### ISSUE TITLE
Take visibility information out of Hyrax Work Types spreadsheet and put them in their own space

### ISSUE THREAD

**Issue by vantuyls** [osulp/sa-content#11]
The visibility mapping information isn't quite appropriate for the Hyrax Work Types spreadsheet. We'd like to capture this information and the mapping elsewhere.

**Comment by zhang4952** [comment]
It is now in its own spreadsheet: https://docs.google.com/spreadsheets/d/1oEjhXVdtsC6fnavMqFrc91HeoVg5023ImzR-nTPfBW0/edit?usp=sharing

**Comment by vantuyls** [comment]
this is being implemented in dspace2hydra, but is documented in the spreadsheet linked above.
