### ISSUE TITLE
Need a predicate for Degree Level

### ISSUE THREAD

**Issue by vantuyls** [osulp/sa-content#19]
it may be worth taking another look to see if a predicate exists for Bachelor's, Master's, Doctoral, etc.

**Comment by vantuyls** [comment]
@wickr will look for a predicate today (last ditch effort) - if none is found, we will create an ONS predicate.

**Comment by wickr** [comment]
Found http://purl.org/NET/UNTL/vocabularies/degree-information/#level

They also have a controlled vocabulary for levels but it's not fully complete for our needs: http://digital2.library.unt.edu/vocabularies/degree-levels/
