### ISSUE TITLE
Determine how to handle Volume and Issue information for Articles

### ISSUE THREAD

**Issue by vantuyls** [osulp/sa-content#20]
Currently, these are in a http://purl.org/dc/terms/isPartOfSeries field.

**Comment by mlv611** [comment]
Filled out in spreadsheet also, @vantuyls

**Comment by vantuyls** [comment]
do @wickr comments on https://github.com/osulp/sa-content/issues/22 apply to this one too?

**Comment by wickr** [comment]
Think we're good now with the volume/issue predicates.
