### ISSUE TITLE
Need predicate for Journal Title

### ISSUE THREAD

**Issue by vantuyls** [osulp/sa-content#22]

**Comment by mlv611** [comment]
@vantuyls spreadsheet including this is finished.

**Comment by wickr** [comment]
http://purl.org/dc/terms/isPartOfSeries  does not exist as a valid term.

In the Hyrax Work Types doc, for Journal Title, isPartOf is there on the 'Article' sheet. But that's also used for Series on the 'OER' sheet. There's other options, I left notes on the 'Article' sheet.

**Comment by mlv611** [comment]
@vantuyls @vantuyls Use isPartOf.  One of them got changed and then somehow the others followed.

**Comment by janemnichols** [comment]
https://docs.google.com/spreadsheets/d/1IwifC3NBIHqBhNBZxQNlqYr6u-xBHYFs-025xNYaMik/edit#gid=172570857

and 

https://docs.google.com/spreadsheets/d/1dO3jQ1odDCNwOi3HGfa5-pngO3b9mIb-ccDJ8aZnAdE/edit#gid=0

**Comment by revgum** [comment]
It was decided that "Bibtex has 'hasJournal' for journal name. http://zeitkunst.org/bibtex/0.2/bibtex.owl#hasJournal" is the right predicate

**Comment by zhang4952** [comment]
Hui will query DSpace to find out values stored in alt-title and ispartofseries to assist the decision of whether alt-title should be used for journal title.

**Comment by wickr** [comment]
@zhang4952 to clarify, we're not deciding on whether we should use title.alternative for journal title in Hyrax. We're curious if any journal titles currently exist in title.alternative in DSpace and need to be mapped/moved to the new journal title predicate. And if there are any other 'real' alternative titles that would prevent mapping everything to journal title. So yes if you can pull both lists of current values it would be helpful to analyze them and see how to map them.

**Comment by zhang4952** [comment]
Please see attached two spreadsheets with values in DSpace: 2,500 items have alternative titles and most of them sounds like series titles, 200 items have relation.ispartofseries and most of them (except a few clear errors) are journal titles. So, the title.alternative could be mapped to something like series title (?), while ispartofseries mapped to series title as well?
@mlv611 @wickr 
[alternative-title.xlsx](https://github.com/osulp/sa-content/files/883872/alternative-title.xlsx)
[ispartofseries.xlsx](https://github.com/osulp/sa-content/files/883874/ispartofseries.xlsx)

**Comment by vantuyls** [comment]
@wickr @zhang4952 do you know where we are with this?

**Comment by zhang4952** [comment]
My opinion: use isPartofseries as predicate for journal title because alt-title has mixed of contents

**Comment by vantuyls** [comment]
alt-title data looks pretty clean to me. 

i'm perplexed as to what to do with the ispartofseries data

**Comment by zhang4952** [comment]
I will correct my early comments: journal title already has a predicate, and the reason to create the isPartofSeries and alt-title spreadsheets is to check whether they contain values of journal titles. https://github.com/osulp/sa-content/issues/37

**Comment by vantuyls** [comment]
solved: 

map alternative title and ispartofseries based on the metadata application profile. 

map isPartofSeries to in_series
map alt-title to alt-title
