### ISSUE TITLE
Talk to Graduate School about Academic Year for historic ETDs

### ISSUE THREAD

**Issue by vantuyls** [osulp/sa-content#25]
Talk to Julie Kurtz about defining academic year for historic ETDs to help with reporting

**Comment by luisgreg99** [comment]
reference to https://github.com/osulp/Scholars-Archive/issues/499

**Comment by vantuyls** [comment]
email has been sent to Julie Kurtz, awaiting response.

**Comment by vantuyls** [comment]
We need to have a look at the metadata for graduation date to see how messy it is. Graduate School needs a little more information about the scope of the problem before they can make a decision. 

@zhang4952

**Comment by zhang4952** [comment]
Here is the spreadsheet by graduation year: 
[Graduation_year.xlsx](https://github.com/osulp/sa-content/files/883511/Graduation_year.xlsx)

@vantuyls

**Comment by vantuyls** [comment]
Issue resolved after discussion with Julie Kurtz at the graduate school. We determined that each ETD has the commencement date, which is the second half of the graduation year. 

Example: commencement date 2017 is academic year 2016-2017.
