### ISSUE TITLE
Assign Admin_Set for collections with mixed item types

### ISSUE THREAD

**Issue by zhang4952** [osulp/sa-content#29]
There are few collections with mixed item types, see them with 'Admin_Set' set to yellow color: https://docs.google.com/spreadsheets/d/1Z_G-LO65NYf5BqkMH0koLzG5DoZ8KD3yAapViWCxiJw/edit#gid=0. 
Background: the migration script uses the owning_collection to identify admin_set from the spreadsheet above, which is safe according to data. For instance, 1957/89||1957/18497 will be ETD and 1957/43909||1957/18497 will be Default. However, a few collections like 1957/1339 have mixed dc.type and cannot decide the Admin_Set automatically.
@vantuyls @revgum

**Comment by vantuyls** [comment]
Hui will generate a spreadsheet with Colleciton Handle, Item Handle, and dc.type and stevie will assign admin sets. go team.

**Comment by zhang4952** [comment]
collection_handles:
1957/1339, 1957/18090, 1957/7864, 1957/12309, 1957/48899, 1957/13727, 1957/8163, 1957/16561

**Comment by zhang4952** [comment]
spreadsheets copied to Google drive: https://drive.google.com/open?id=0Bxlj1p4QYIzjQXNKdklKbGhpZVE
@vantuyls
