### ISSUE TITLE
Add historic academic units to ONS

### ISSUE THREAD

**Issue by vantuyls** [osulp/sa-content#3]
Historic academic units need to be added to ONS so that we can build out connections among academic units for reporting in SA@OSU

**Comment by vantuyls** [comment]
this is in process. json-ld file has been created and upload will happen soon.

**Comment by vantuyls** [comment]
@straleyb where are we on this one?

**Comment by wickr** [comment]
Brandon generated the JSON-LD files for me that I then imported into opaquenamespace.org, back in March.
