### ISSUE TITLE
Need to identify names for non-academic units in DSpace

### ISSUE THREAD

**Issue by vantuyls** [osulp/sa-content#30]
We have a handful of non-academic names that will want to be faceted or otherwise queryable. We need to identify whether these already have names. This is the current list:

Other Affiliations:
- [x] Center for Genome Research and Biocomputing - http://opaquenamespace.org/ns/subject/OregonStateUniversityCenterForGenomeResearchAndBiocomputing
- [x] Extension Service - http://id.loc.gov/authorities/names/n79115395
- [x] Extension Service and Agricultural Experiment Station - http://id.loc.gov/authorities/names/n80126175
- [x] Engineering Experiment Station - http://id.loc.gov/authorities/names/n82166978
- [x] OSU Cascades - http://www.wikidata.org/entity/Q7101371
- [x] Hatfield Marine Science Center - http://id.loc.gov/authorities/names/n84131837
- [x] Institute for Natural Resources - http://id.loc.gov/authorities/names/no2006063387
- [x] Honors College - http://opaquenamespace.org/ns/subject/OregonStateUniversityHonorsCollege
- [x] Faculty Senate Library Committee - http://opaquenamespace.org/ns/subject/OregonStateUniversityFacultySenateLibraryCommittee
- [x] Linus Pauling Institute - http://www.wikidata.org/entity/Q3151762
- [x] Northwest National Marine Renewable Energy Center (NNMREC) Publications - http://www.wikidata.org/entity/Q7060130
- [x] Oregon Marine Renewable Energy Environmental Science Conference Proceedings - http://opaquenamespace.org/ns/subject/OregonMarineRenewableEnergyEnvSciConference
- [x] Oregon Wave Energy Trust - http://id.loc.gov/authorities/names/no2011009181
- [x] Oregon Explorer - http://opaquenamespace.org/ns/subject/OregonExplorer
- [x] Oregon Department of Fish and Wildlife - http://id.loc.gov/authorities/names/n81053266
- [x] OSU Press - http://id.loc.gov/authorities/names/n82039655
- [x] President's Office - http://opaquenamespace.org/ns/subject/OregonStateUniversityPresidentsOffice
- [x] Registrar's Office - http://opaquenamespace.org/ns/subject/OregonStateUniversityRegistrarsOffice
- [x] Rural Studies Program - http://opaquenamespace.org/ns/subject/OregonStateUniversityRuralStudiesProgram
- [x] Bioenergy Minor Program - http://opaquenamespace.org/ns/subject/OregonStateUniversityBioenergyMinorProgram
- [x] Student Affairs - http://opaquenamespace.org/ns/subject/OregonStateUniversityDivisionOfStudentAffairs	
- [x] Celebration of Undergraduate Excellence - http://opaquenamespace.org/ns/subject/OregonStateUniversityCelebrationOfUndergraduateExcellence
- [x] Library Undergraduate Research Awards - http://opaquenamespace.org/ns/subject/OregonStateUniversityLibraryUndergraduateResearchAwards
- [x] University Housing & Dining Services - http://opaquenamespace.org/ns/subject/OregonStateUniversityHousingDiningServices
- [x] University Information Technology Committee - http://opaquenamespace.org/ns/subject/OregonStateUniversityInformationTechnologyCommittee
- [x] University Libraries - http://id.loc.gov/authorities/names/n00020491
- [x] Urban League of Portland - http://id.loc.gov/authorities/names/no2011149633
- [x] Women's Center - http://opaquenamespace.org/ns/subject/OregonStateUniversityWomensCenter
- [x] Writing Intensive Curriculum - http://opaquenamespace.org/ns/subject/OregonStateUniversityWritingIntensiveCurriculum

**Comment by vantuyls** [comment]
Look in LCNAF or LCSH for these

**Comment by vantuyls** [comment]
The following were not found in LOC or wikidata:

- [x] Center for Genome Research and Biocomputing
- [x] Honors College
- [x] Faculty Senate Library Committee
- [x] Oregon Marine Renewable Energy Environmental Science Conference Proceedings 
- [x] Oregon Explorer
- [x] President's Office
- [x] Registrar's Office
- [x] Rural Studies Program
- [x] Bioenergy Minor Program
- [x] Student Affairs
- [x] Celebration of Undergraduate Excellence
- [x] Library Undergraduate Research Awards
- [x] University Housing & Dining Services
- [x] University Information Technology Committee
- [x] Women's Center
- [x] Writing Intensive Curriculum

**Comment by vantuyls** [comment]
@wickr we ought to talk about this today

**Comment by wickr** [comment]
Existing terms were found, Steve made terms for those that didn't exist and they're now live.
