### ISSUE TITLE
Create FAQ for Rights and Licenses

### ISSUE THREAD

**Issue by vantuyls** [osulp/sa-content#33]
A basic FAQ that helps users understand what rightstatements and licenses mean.

**Comment by mwillihooper** [comment]
Started here: https://docs.google.com/a/oregonstate.edu/document/d/15u9v-NcK2dDMiriTDon-MfVk3b_PuLbGneJiPsi9SVo/edit?usp=sharing

What else do we need? Are we going to have a separate module for copyright for authors/depositors?

**Comment by vantuyls** [comment]
moved to https://github.com/osulp/Scholars-Archive/issues/1101
