### ISSUE TITLE
need list of degree names from DSpace

### ISSUE THREAD

**Issue by vantuyls** [osulp/sa-content#35]
in order to create local authorities for Degree Name, we need a list of unique degree names that currently exist in DSpace.

**Comment by vantuyls** [comment]
we'll determine the list of values for Degree Level from the list provided for Degree Name.

**Comment by zhang4952** [comment]
Bachelor of Science (B.S.)
Doctor of Education (Ed.D.)
Doctor of Philosophy (Ph.D.)
Electrical Engineer (E.E.)
Honors Bachelor of Arts (HBA)
Honors Bachelor of Fine Arts (HBFA)
Honors Bachelor of Science (HBS)
Master of Agriculture (M.Ag.)
Master of Arts (M.A.)
Master of Arts in Interdisciplinary Studies (M.A.I.S.)
Master of Education (Ed.M.)
Master of Fine Arts (M.F.A.)
Master of Forestry (M.F.)
Master of Ocean Engineering (M.Oc.E.)
Master of Public Health (M.P.H.)
Master of Science (M.S.)
