### ISSUE TITLE
Clean up isPartOf content

### ISSUE THREAD

**Issue by vantuyls** [osulp/sa-content#38]
Some content that moved from DSpace to Hydra used the mythical predicate isPartOfSeries and was, largely, a combination of Journal Title, Volume, and Number. We forewent cleaning this up pre-migration (because there wasn't a place to put the Volume and Number values in DSpace) in favor of cleaning these up post-migration. 

SO: in the spreadsheet linked below, please clean up the metadata by separating Journal Title, Volume, Number and any additional information into appropriate form fields.

**Comment by mlv611** [comment]
@vantuyls Where is the spreadsheet?

**Comment by vantuyls** [comment]
it hasn't been created yet. @zhang4952 is going to generate it soon.

**Comment by zhang4952** [comment]
The spreadsheet is in the Google drive: https://docs.google.com/spreadsheets/d/10KnwYNVvJmHohJNFDv1mh_h6wAJ6fj2Cfgl3C1jm2Go/edit?usp=sharing, there are ~21,000 items with legitimate values. It will take 'significant' effort to clean it because they are in wide spreading formats.
@vantuyls @mlv611

**Comment by zhang4952** [comment]
@vantuyls @mlv611

**Comment by vantuyls** [comment]
moved to: https://github.com/osulp/Scholars-Archive/issues/1100
