### ISSUE TITLE
create list of collections that have had activity in the past 6 months

### ISSUE THREAD

**Issue by vantuyls** [osulp/sa-content#41]
I would like to use this list to help me know who to contact to let them know migration is happening soon and there may be some service disruptions.

**Comment by zhang4952** [comment]
Post it to Google drive: https://docs.google.com/spreadsheets/d/1Vj0_CWJDDGPepG1fCtagzWYLsUmIClo5Bw3jMaeVzfc/edit?usp=sharing check the second column for collections have recent update. 
@vantuyls
