### ISSUE TITLE
Degree field dates need to be formatted for ONS

### ISSUE THREAD

**Issue by vantuyls** [osulp/sa-content#42]
Need to take the data from the Cleaner Degrees tab of the below spreadsheet and create EDTF date ranges for each item like:

Agricultural Engineering 1946, 1948/1949, 1956, 1959, 1987 

https://docs.google.com/spreadsheets/d/14lL_7Z8KPyYWWyn6fFNdrGLhAKiKqcyLnrDRumLxATA/edit#gid=1056514444

**Comment by vantuyls** [comment]
@wickr i think this is done, right?

**Comment by wickr** [comment]
yes, completed: http://opaquenamespace.org/ns/osuDegreeFields
