### ISSUE TITLE
Deposit Extension publications

### ISSUE THREAD

**Issue by boockm** [osulp/sa-content#45]
Elizabeth Nielsen requested the deposit of the following item to SA@OSU after it is digitized by the DPU:

Agricultural Experiment Station Special Report 899
Malheur County Crop Research 1991
Published in June 1992

Brian, maybe you could attach the file to this github ticket then I can deposit to the new SA@OSU?

**Comment by tvc15brian** [comment]
Seems that the file has to be below 10mb. This is a 220 page PDF and it's 133mb.

**Comment by boockm** [comment]
Ah, shared drive?

**Comment by tvc15brian** [comment]
https://oregonstate.box.com/s/dqhgb08ubd1sjsdjeen7r28kizounjio

**Comment by boockm** [comment]
Deposit finished. Just awaiting approval.

**Comment by boockm** [comment]
http://ir.library.oregonstate.edu/concern/eesc_publications/9880vw55z
