### ISSUE TITLE
upload Karow and Lutz report

### ISSUE THREAD

**Issue by vantuyls** [osulp/sa-content#46]
Karow and Lutz PDF - in Steve's SAContent folder

**Comment by simholt** [comment]
I uploaded the Karow & Lutz article with barebones metadata. It is set to Private.

http://ir.library.oregonstate.edu/concern/articles/m326m670w

Since this is from OHQ, I'm not sure what's appropriate for License, Rights Statement, or Publisher.

Please advise!

**Comment by vantuyls** [comment]
advice offered. @simholt close the issue if it is finished, if not, lets follow up.

**Comment by vantuyls** [comment]
actually, after taking a look at the item, i think this is complete.
