### ISSUE TITLE
Change 'Thesis' Resource Type to valid one (undergrad, master's, honors)

### ISSUE THREAD

**Issue by wickr** [osulp/sa-content#50]
There are about 2500 works with 'Thesis' as a Resource Type, but it's not on the authority list. You can't make any other edits or updates to these works until that is resolved (Save button is disabled). 

Will likely need to check Degree Level, Degree Name, or some other fields to figure out what best determines what to change a given Resource Type to.

**Comment by vantuyls** [comment]
@zhang4952 can you extract degree level, degree name, and degree field, and ID for these items and place them in a spreadsheet?

**Comment by vantuyls** [comment]
moved to https://github.com/osulp/Scholars-Archive/issues/1097
