### ISSUE TITLE
Only 1 value in Conference Name facet

### ISSUE THREAD

**Issue by wickr** [osulp/sa-content#51]
There should probably be more values here. Was the data not in DSpace to start with? Did the data get migrated to a wrong or incorrect predicate? 

If we need to pull data out of other field(s) then this may be a project Sarah can help with.

**Comment by vantuyls** [comment]
i suspect this is erroneous mapping. I'll talk to @simholt tomorrow about this. 

@zhang4952 is there any way you can think of to identify conference proceedings in DSpace?

**Comment by wickr** [comment]
@vantuyls @boockm didn't think the data was in the records as a separate field, but it was in the Collection name. He added 'conference name' column and values to this spreadsheet: https://docs.google.com/spreadsheets/d/1Z_G-LO65NYf5BqkMH0koLzG5DoZ8KD3yAapViWCxiJw/edit#gid=0

So we can probably do this in a batch update.

**Comment by vantuyls** [comment]
moved to https://github.com/osulp/Scholars-Archive/issues/1096
