### ISSUE TITLE
Honors college theses mapped to wrong worktype/admin set

### ISSUE THREAD

**Issue by simholt** [osulp/sa-content#54]
Need to separate honors college theses from undergrad theses (unless they are also somewhere else?) and move to honors college worktype/admin set. 

Example:
https://ir.library.oregonstate.edu/concern/undergraduate_thesis_or_projects/12579x96m?locale=en

**Comment by simholt** [comment]
Also:
https://ir.library.oregonstate.edu/concern/undergraduate_thesis_or_projects/j3860c57t?locale=en

**Comment by vantuyls** [comment]
moved to https://github.com/osulp/Scholars-Archive/issues/1092
