### ISSUE TITLE
Determine a method for populating the drop-down list for degrees

### ISSUE THREAD

**Issue by vantuyls** [osulp/sa-content#6]
In order to inform the ingest form's drop downs for Degree Level, Degree Name, and Degree Field, we need to identify what degrees were conferred to graduate and undergraduate students with content in SA@OSU from 2011-2016. 

Need: a normalized list of all of the unique degrees for that time period.

**Comment by vantuyls** [comment]
Edited title to allow flexibility in approach. 

One approach is to create a list of degrees conferred over the past few (five?) years and use that to populate the controlled vocabulary. 

Another approach is to use data from Banner (?) to populate the list with all of the degrees that are available to be conferred in a given year. 

To Do:
- [ ] Determine which approach, above, to use
- [ ] Generate a new issue to implement that approach

**Comment by mlv611** [comment]
I believe we decided to compare the list that I generated from the past five years with the list that Margaret will generate from Banner and see how much they deviate from each other.

**Comment by mlv611** [comment]
@mellinma have you gotten the CORE list for comparison?

**Comment by mlv611** [comment]
The information Margaret got from CORE isn't what we need, so we will go with my list.  @vantuyls @revgum @zhang4952
