### ISSUE TITLE
build a list of the main work types needed for SA@OSU

### ISSUE THREAD

**Issue by vantuyls** [osulp/sa-content#7]
Keeping in mind the relationship between work types (essentially what metadata is required) and workflow.

**Comment by vantuyls** [comment]
Previous conversations with @zhang4952 and @revgum suggest these as a starting point for the Admin Sets we will need (combination of work type and workflow):
- [ ] Generic Works - default admin set
- [ ] Faculty Articles - generic work type with specific workflow
- [ ] Graduate Theses and Dissertations - thesis/capstone work type with graduate school workflow
- [ ] Undergraduate Theses and Grad/Undergrad Capstone Projects - thesis/capstone work type with undergraduate and/or honors college style workflow
- [ ] Extension Publications - generic work type (?) with extension workflow
- [ ] Datasets - dataset work type and dataset workflow

@mlv611

**Comment by mlv611** [comment]
I will put a column for each of these in the Sufia DD and try to figure out which predicates should go with each admin set.  @vantuyls please feel free to add your input to the DD.

**Comment by vantuyls** [comment]
Thanks @mlv611 - can you start working from the document called Hyrax Work Types? We'd like to collect the work types there.

**Comment by mlv611** [comment]
Sure, @vantuyls.

**Comment by boockm** [comment]
@mlv611 Just had a chat with @vantuyls about adding Conference Presentations (generic work type and conference presentations workflow?) as a work type. There is a fair amount of this content already in SA and likely to be more in the future.

**Comment by mlv611** [comment]
@boockm, sounds like a good idea.  Thanks.

**Comment by vantuyls** [comment]
Hmm. I think we need to brainstorm a bit around this. Work Type and Workflow are what make up the Admin Set for deposit. What i've laid out in that checklist above is probably more about Admin Set than it is about Work Type. Can we get away with these work types:
- [ ] Generic Work
- [ ] Theses (including undergrad, grad thesis, dissertation, capstone project)
- [ ] Extension Publications (though does this need it's own metadata and form or is it similar enough?)
- [ ] Proceedings

@mlv611 @zhang4952 @revgum

**Comment by zhang4952** [comment]
I think Extension and Proceedings just use the 'default' metadata in DSpace now, so we should not need new work types for them unless they need different forms in Hydra (and the same situation to dataset as well).

**Comment by vantuyls** [comment]
Okay, scrap that one.

**Comment by vantuyls** [comment]
Moving all workflow, work type, and admin set descriptions to a single spreadsheet:
https://docs.google.com/spreadsheets/d/1iilzOAuanmcVcpU0cq81fl40XYP0Dxs0yp9JZw6us3w/edit?usp=sharing

This sheet will be useful for reference, but other, more specific spreadsheets (e.g. Hyrax Work Types) will be required for detailed reference (e.g. for metadata fields, predicates, etc.)
